version: '3.3'
services:
  user-service:
    image:  user-profile:v1
    networks:
      - user-profile
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8093:8083/tcp
    container_name: user-service
    networks:
      - user-profile
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'user-profile'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'welcome'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - user-profile
    # Names our volume
volumes:
  my-db:
networks:
  user-profile:
    driver: bridge
