spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user_service?createDatabaseIfNotExist=true&useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: password

    initialization-mode: always
    hikari:
      maximum-pool-size: 10
mybatis:
  mapper-locations: classpath*:/mybatis/*.xml # Tells mybatis to look in resources/mybatis for XML mappers
  type-aliases-package: com.datetest.userprofile.models